import './globals.css'
import { Inter,Poppins } from 'next/font/google'
const poppins = Poppins({ weight:"500",subsets: ['latin'] })
export const metadata = {
  title: 'chatApp nextV',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}
      </body>
    </html>
  )
}
